-- 创建统一的流程数据表
-- 迁移时间: 2025-01-31
-- 描述: 建立统一的流程数据存储结构

SET client_encoding = 'UTF8';

-- 1. 创建spms_process_data表
CREATE TABLE spms_process_data (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    process_instance_id VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    process_definition_key VARCHAR(255) NOT NULL,
    form_type VARCHAR(50) NOT NULL DEFAULT 'OTHER',
    form_data TEXT,
    business_data TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    approval_comment TEXT,
    version INTEGER DEFAULT 0,

    -- 审计字段
    created_at BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()) * 1000,
    updated_at BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()) * 1000,
    created_by_id BIGINT,
    updated_by_id BIGINT,

    -- 外键约束
    CONSTRAINT fk_process_data_user FOREIGN KEY (user_id) REFERENCES spms_user(id),
    CONSTRAINT fk_process_data_created_by FOREIGN KEY (created_by_id) REFERENCES spms_user(id),
    CONSTRAINT fk_process_data_updated_by FOREIGN KEY (updated_by_id) REFERENCES spms_user(id)
);

-- 2. 创建索引
CREATE INDEX idx_process_data_process_instance_id ON spms_process_data(process_instance_id);
CREATE INDEX idx_process_data_user_id ON spms_process_data(user_id);
CREATE INDEX idx_process_data_process_definition_key ON spms_process_data(process_definition_key);
CREATE INDEX idx_process_data_status ON spms_process_data(status);
CREATE INDEX idx_process_data_form_type ON spms_process_data(form_type);
CREATE INDEX idx_process_data_created_at ON spms_process_data(created_at);

-- 3. 添加表注释
COMMENT ON TABLE spms_process_data IS '统一的流程数据表';
COMMENT ON COLUMN spms_process_data.id IS '主键ID';
COMMENT ON COLUMN spms_process_data.process_instance_id IS '流程实例ID';
COMMENT ON COLUMN spms_process_data.user_id IS '用户ID';
COMMENT ON COLUMN spms_process_data.process_definition_key IS '流程定义键';
COMMENT ON COLUMN spms_process_data.form_type IS '表单类型: LEAVE, OTHER';
COMMENT ON COLUMN spms_process_data.form_data IS '表单数据(JSON格式)';
COMMENT ON COLUMN spms_process_data.business_data IS '业务数据(JSON格式)';
COMMENT ON COLUMN spms_process_data.status IS '状态: DRAFT, SUBMITTED, APPROVED, REJECTED, CANCELLED';
COMMENT ON COLUMN spms_process_data.approval_comment IS '审批意见';
COMMENT ON COLUMN spms_process_data.version IS '版本号(乐观锁)';
