openapi: 3.0.3
info:
  title: Holiday API
  description: Holiday management REST API for SPMS Timecard module
  version: 1.0.0
servers:
  - url: /api/v1/timecard/holidays
    description: Holiday API base path

tags:
  - name: Holidays
    description: Holiday management operations

paths:
  /:
    get:
      tags:
        - Holidays
      summary: Get holidays
      description: Get holidays for a specific month or year
      operationId: getHolidays
      parameters:
        - name: month
          in: query
          description: Month in format YYYY-MM
          required: false
          schema:
            type: string
            pattern: '^\d{4}-\d{2}$'
        - name: year
          in: query
          description: Year in format YYYY
          required: false
          schema:
            type: string
            pattern: '^\d{4}$'
      responses:
        '200':
          description: Holidays retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HolidayDTO'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      tags:
        - Holidays
      summary: Create holiday
      description: Create a new holiday
      operationId: createHoliday
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HolidayCreateRequest'
      responses:
        '201':
          description: Holiday created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HolidayDTO'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          description: Holiday already exists
        '500':
          $ref: '#/components/responses/InternalServerError'

  /{id}:
    get:
      tags:
        - Holidays
      summary: Get holiday by ID
      description: Get a specific holiday by ID
      operationId: getHolidayById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Holiday retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HolidayDTO'
        '404':
          description: Holiday not found
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

    put:
      tags:
        - Holidays
      summary: Update holiday
      description: Update an existing holiday
      operationId: updateHoliday
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HolidayUpdateRequest'
      responses:
        '200':
          description: Holiday updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HolidayDTO'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          description: Holiday not found
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      tags:
        - Holidays
      summary: Delete holiday
      description: Delete a holiday by ID
      operationId: deleteHoliday
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Holiday deleted successfully
        '404':
          description: Holiday not found
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /import:
    post:
      tags:
        - Holidays
      summary: Import holidays from Excel
      description: Import holidays from Excel file
      operationId: importHolidays
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Excel file containing holidays
      responses:
        '200':
          description: Holidays imported successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportResultDTO'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /export:
    get:
      tags:
        - Holidays
      summary: Export holidays to Excel
      description: Export holidays to Excel file
      operationId: exportHolidays
      parameters:
        - name: year
          in: query
          description: Year to export (optional, exports all if not specified)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Excel file downloaded
          content:
            application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
              schema:
                type: string
                format: binary
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    HolidayDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        date:
          type: string
          format: date
          description: Holiday date
        name:
          type: string
          description: Holiday name
        country:
          type: string
          description: Country code (optional, for multi-country support)
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    HolidayCreateRequest:
      type: object
      required:
        - date
        - name
      properties:
        date:
          type: string
          format: date
        name:
          type: string
        country:
          type: string
          description: Country code (optional)

    HolidayUpdateRequest:
      type: object
      properties:
        date:
          type: string
          format: date
        name:
          type: string
        country:
          type: string

    ImportResultDTO:
      type: object
      properties:
        success:
          type: boolean
        totalRecords:
          type: integer
        importedRecords:
          type: integer
        failedRecords:
          type: integer
        errors:
          type: array
          items:
            type: object
            properties:
              row:
                type: integer
              message:
                type: string

    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

