openapi: 3.0.3
info:
  title: Project Task Activity API
  description: Project-Task-Activity management REST API for SPMS Timecard module
  version: 1.0.0
servers:
  - url: /api/v1/timecard/projects/tasks
    description: Project Task Activity API base path

tags:
  - name: ProjectTaskActivity
    description: Project-Task-Activity combination management

paths:
  /:
    get:
      tags:
        - ProjectTaskActivity
      summary: Get project task activities
      description: Get list of project-task-activity combinations
      operationId: getProjectTaskActivities
      parameters:
        - name: projectCode
          in: query
          description: Filter by project code
          required: false
          schema:
            type: string
        - name: taskNumber
          in: query
          description: Filter by task number
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Project task activities retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectTaskDTO'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      tags:
        - ProjectTaskActivity
      summary: Create project task activity
      description: Create a new project-task-activity combination
      operationId: createProjectTaskActivity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectTaskCreateDTO'
      responses:
        '201':
          description: Project task activity created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectTaskDTO'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          description: Project task activity already exists
        '500':
          $ref: '#/components/responses/InternalServerError'

  /{id}:
    get:
      tags:
        - ProjectTaskActivity
      summary: Get project task activity by ID
      description: Get a specific project-task-activity by ID
      operationId: getProjectTaskActivityById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Project task activity retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectTaskDTO'
        '404':
          description: Project task activity not found
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

    put:
      tags:
        - ProjectTaskActivity
      summary: Update project task activity
      description: Update an existing project-task-activity
      operationId: updateProjectTaskActivity
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectTaskUpdateDTO'
      responses:
        '200':
          description: Project task activity updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectTaskDTO'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          description: Project task activity not found
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      tags:
        - ProjectTaskActivity
      summary: Delete project task activity
      description: Delete a project-task-activity by ID
      operationId: deleteProjectTaskActivity
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Project task activity deleted successfully
        '404':
          description: Project task activity not found
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    ProjectTaskDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        projectCode:
          type: string
          description: Project code
        projectName:
          type: string
          description: Project name
        taskNumber:
          type: string
          description: Task number
        taskName:
          type: string
          description: Task name
        activity:
          type: string
          description: Activity description
        status:
          type: string
          enum: [ACTIVE, COMPLETED]
          description: Project status

    ProjectTaskCreateDTO:
      type: object
      required:
        - projectCode
        - taskNumber
        - activity
      properties:
        projectCode:
          type: string
        taskNumber:
          type: string
        activity:
          type: string

    ProjectTaskUpdateDTO:
      type: object
      properties:
        projectCode:
          type: string
        taskNumber:
          type: string
        activity:
          type: string
        status:
          type: string
          enum: [ACTIVE, COMPLETED]

    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

